### ISSUE TITLE
Fine tuning PLBART on Devign or a new dataset

### ISSUE THREAD

**Issue by Kamel773** [wasiahmad/PLBART#38]
Hi @wasiahmad,

Thank you for sharing the source code and dataset with us. 

How can I fine tune PLBART (training) on Devign dataset or a new dataset?

Kamel

**Comment by wasiahmad** [comment]
Please follow the README.

**Comment by Kamel773** [comment]
Thank you @wasiahmad, I am still having an error in fine tuning the model. Please have a look at the error below. 



---------------------------------------------------------------------------------------------------------------------
2022-06-29 19:27:02 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-06-29 19:27:02 | INFO | fairseq.utils | rank   0: capabilities =  7.5  ; total memory = 14.756 GB ; name = Tesla T4                                
2022-06-29 19:27:02 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-06-29 19:27:02 | INFO | fairseq_cli.train | training on 1 devices (GPUs/TPUs)
2022-06-29 19:27:02 | INFO | fairseq_cli.train | max tokens per GPU = None and max sentences per GPU = 4
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/opt/conda/lib/python3.7/site-packages/fairseq_cli/train.py", line 348, in cli_main
    distributed_utils.call_main(args, main)
  File "/opt/conda/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 187, in call_main
    main(args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/fairseq_cli/train.py", line 106, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/opt/conda/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/opt/conda/lib/python3.7/site-packages/fairseq/trainer.py", line 252, in load_checkpoint
    state = checkpoint_utils.load_checkpoint_to_cpu(filename)
  File "/opt/conda/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 169, in load_checkpoint_to_cpu
    f, map_location=lambda s, l: default_restore_location(s, "cpu")
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by wasiahmad** [comment]
Please make sure you use an environment that follows the package requirements. All the code in this repo is tested, so if something doesn't work, I assume the environment is not properly configured.
