### ISSUE TITLE
argument --user-dir: expected one argument

### ISSUE THREAD

**Issue by saichandrapandraju** [wasiahmad/PLBART#9]
Hi,

I wanted to fine-tune PLBART for Code summarization task. While following the steps, i'm getting below error for `!bash run.sh 0 python` - 
```
usage: fairseq-train [--user-dir USER_DIR]
fairseq-train: error: argument --user-dir: expected one argument
usage: fairseq-generate [--user-dir USER_DIR]
fairseq-generate: error: argument --user-dir: expected one argument
Total: 0
Traceback (most recent call last):
  File "evaluator.py", line 205, in <module>
    res = bleuFromMaps(goldMap, predictionMap)
  File "evaluator.py", line 198, in bleuFromMaps
    return [round(s * 100.0 / num, 2) for s in score]
  File "evaluator.py", line 198, in <listcomp>
    return [round(s * 100.0 / num, 2) for s in score]
ZeroDivisionError: float division by zero
```
Any idea how to proceed further ?

**Comment by wasiahmad** [comment]
Fixed!
